/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/case.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/case.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Extrude3.geometry} material={materials.Mat} position={[0.834, -0.001, 0]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Extrude5.geometry} material={materials.Mat} position={[0.136, -0.151, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Extrude4.geometry} material={materials.Mat} position={[0.136, 0.152, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Extrude11.geometry} material={materials.Mat} position={[0.271, 0, 0.001]} rotation={[0, 1.571, 0]}>
          <mesh geometry={nodes.Extrude13.geometry} material={materials.Mat} position={[0.09, 0.151, -0.001]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Extrude14.geometry} material={materials.Mat} position={[0.089, -0.152, 0]} rotation={[1.553, 0, 0]} />
          <mesh geometry={nodes.Extrude12.geometry} material={materials.Mat} position={[0.179, 0, 0]} rotation={[0, 1.571, 0]} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.Extrude2.geometry} material={materials.Mat} position={[0.744, -0.001, 0]}>
        <mesh geometry={nodes.Extrude8.geometry} material={materials.Mat} position={[-0.091, 0, 0.001]} rotation={[0, -1.571, 0]}>
          <mesh geometry={nodes.Extrude9.geometry} material={materials.Mat} position={[-0.139, 0.152, -0.001]} rotation={[-1.553, 0, 0]} />
          <mesh geometry={nodes.Extrude10.geometry} material={materials.Mat} position={[-0.139, -0.151, 0]} rotation={[Math.PI / 2, 0, 0]} />
        </mesh>
        <mesh geometry={nodes.Extrude7.geometry} material={materials.Mat} position={[0, -0.152, 0]} rotation={[1.553, 0, 0]} />
        <mesh geometry={nodes.Extrude6.geometry} material={materials.Mat} position={[0, 0.152, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/case.gltf')
